### ISSUE TITLE
Recent GUI changes leave no way to clear a search

### ISSUE THREAD

**Issue by redblade7** [minetest-mods/xban2#7]
Hi,

Ever since the improved GUI was added last May, I am unable to "clear the search" and show all the player names (it shows a large amount). Searching for these hidden players works, but backspacing all letters does not show every player like it should/used to.

Thank you!

**Comment by kaeza** [comment]
This is intentional. On large servers, it may need to load thousands of entries, taking excessive amounts of memory and/or bandwidth sending the formspec to the client.

If you want to change the limit, you can edit [this line](https://github.com/minetest-mods/xban2/blob/master/gui.lua#L3).

I can make this a configuration option if it's really needed.
